[package]
name = "ski_renderer"
version = "0.2.0"
edition = "2021"

[dependencies]
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gpx = "0.9"
tiny-skia = "0.11"
glob = "0.3"
indicatif = "0.17"
hex = "0.4"